# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.2.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Thingintouch Attendance Odoo Modules
repo_name: Thingintouch Attendance Odoo Modules
repo_slug: thingsintouch-attendance
travis_apt_packages: []
travis_apt_sources: []
